# Generated by Django 3.2.6 on 2021-08-30 04:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('book_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date reserved')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='date returned')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
