# Generated by Django 3.2.6 on 2021-08-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_reserve_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='value',
            field=models.FloatField(default=50.0),
        ),
    ]
